import type {
  GameState,
  MissionState,
  RegionId,
  SystemId,
  TrainDefinition,
} from "./types";

export const PLATFORM_COSTS = [50, 150, 400, 10_000] as const;
export const LENGTH_COSTS = [30, 90, 1_200, 7_500] as const;
export const TIER_COSTS = [500, 2_000, 8_000, 30_000] as const;
export const CLEANING_MAX = [25, 100, 400, 1_600, 6_000] as const;

export const SYSTEMS: Record<
  SystemId,
  { name: string; icon: string; cost: number; unlockTier: number; description: string }
> = {
  electrification: {
    name: "Electrification",
    icon: "⚡",
    cost: 120,
    unlockTier: 1,
    description: "Adds catenary and unlocks electric services.",
  },
  signaling: {
    name: "Signaling",
    icon: "🚦",
    cost: 280,
    unlockTier: 2,
    description: "Safer, faster dispatching for express trains.",
  },
  roadAccess: {
    name: "Road access",
    icon: "🚕",
    cost: 650,
    unlockTier: 2,
    description: "Builds a drop-off loop with animated cars.",
  },
  amenities: {
    name: "Amenities",
    icon: "☕",
    cost: 420,
    unlockTier: 2,
    description: "Benches, shelter, lights and a platform kiosk.",
  },
  maintenance: {
    name: "Maintenance yard",
    icon: "🔧",
    cost: 1_800,
    unlockTier: 3,
    description: "A service siding for long-distance stock.",
  },
  advancedSignaling: {
    name: "ETCS test package",
    icon: "📡",
    cost: 5_000,
    unlockTier: 4,
    description: "Advanced signaling needed by the ICE-S record run.",
  },
};

const source = {
  dbRegio: "https://www.dbregio.de/schiene/zugverkehre",
  dbFleet: "https://ir.deutschebahn.com/fileadmin/Englisch/2025e/DB24_Quality_Report.pdf",
  rs1: "https://www.stadlerrail.com/api/docs/x/fec656e35b/rszero_hemu_en.pdf",
  desiroClassic: "https://press.siemens.com/global/en/pressrelease/consortium-develops-safe-remote-controlled-system-ai-based-obstacle-detection-rail",
  lint41: "https://www.alstom.com/de/press-releases-news/2009/11/Deutsche-Bahn-bestellt-16-Coradia-Lint-Regionalzuge-20091127",
  desiroHC: "https://press.siemens.com/global/de/pressemitteilung/db-regio-bayern-und-siemens-mobility-unterzeichnen-vertrag-ueber-31-regionalzuege",
  metronom: "https://www.der-metronom.de/unternehmen/ueber-uns/",
  nightjet:
    "https://www.nightjet.com/dam/jcr%3A6d74c6d1-0c5e-44a2-8b25-5e08c2a51bdb/folder-nightjet-promo-deutschland-de.pdf",
  sbb: "https://www.sbb.ch/en/travel-information/services-on-train/our-trains/giruno.html",
  iceS: "https://www.deutschebahn.com/de/konzern/Im-Fokus/-S-wie-Speed-Der-Hochgeschwindigkeitsmesszug-der-DB-7594140",
  steam: "https://www.dbmuseum.de/koblenz/fahrzeuge/01-1100",
  cd: "https://www.ceskedrahy.cz/sites/default/files/2025-10/25-10-01_PB_Speisewagen_ComfortJets_Berliner_0.pdf",
  flix: "https://corporate.flix.com/flix-brands/",
};

export const TRAINS: TrainDefinition[] = [
  {
    id: "br650",
    name: "DB Class 650 Regio-Shuttle RS1",
    operator: "DB Regio",
    tier: 1,
    kind: "scheduled",
    style: "dmu",
    cars: 1,
    dwell: [10, 14],
    payout: [10, 16],
    spawnWeight: 5,
    requirements: { platforms: 1, lengthLevel: 1, systems: [] },
    modelKey: "br650",
    colors: { body: "#d9dde0", accent: "#d71920", roof: "#8c969b", windows: "#193847" },
    fact: "A compact single-car diesel railbus built for lightly used regional lines.",
    source: source.rs1,
  },
  {
    id: "br642",
    name: "DB Class 642 Desiro Classic",
    operator: "DB Regio",
    tier: 1,
    kind: "scheduled",
    style: "dmu",
    cars: 2,
    dwell: [11, 15],
    payout: [14, 22],
    spawnWeight: 4,
    requirements: { platforms: 1, lengthLevel: 1, systems: [] },
    modelKey: "br642",
    colors: { body: "#e2e4e5", accent: "#c8102e", roof: "#858b8e", windows: "#183745" },
    fact: "The two-car Desiro Classic is widely used on German regional routes.",
    source: source.desiroClassic,
  },
  {
    id: "br648",
    name: "DB Class 648 LINT 41",
    operator: "DB Regio",
    tier: 1,
    kind: "scheduled",
    style: "dmu",
    cars: 2,
    dwell: [12, 16],
    payout: [18, 30],
    spawnWeight: 3,
    requirements: { platforms: 1, lengthLevel: 2, systems: [] },
    modelKey: "br648",
    colors: { body: "#e7e8e8", accent: "#df1027", roof: "#7f898e", windows: "#153744" },
    fact: "LINT 41 units pair a low floor with flexible regional operation.",
    source: source.lint41,
  },
  {
    id: "desiro-hc",
    name: "Siemens Desiro HC Regional-Express",
    operator: "DB Regio",
    tier: 2,
    kind: "scheduled",
    style: "regional",
    cars: 4,
    dwell: [12, 17],
    payout: [55, 90],
    spawnWeight: 4,
    requirements: { platforms: 2, lengthLevel: 2, systems: ["electrification"] },
    modelKey: "desiro-hc",
    colors: { body: "#f1f1ed", accent: "#cc132c", roof: "#67747b", windows: "#133946" },
    fact: "Desiro HC combines single-deck end cars with high-capacity double-deck centre cars.",
    source: source.desiroHC,
  },
  {
    id: "metronom",
    name: "metronom Double-Deck Express",
    operator: "metronom",
    tier: 2,
    kind: "scheduled",
    style: "double",
    cars: 6,
    dwell: [14, 18],
    payout: [80, 125],
    spawnWeight: 3,
    requirements: { platforms: 2, lengthLevel: 3, systems: ["electrification", "signaling"] },
    modelKey: "metronom",
    colors: { body: "#f4f1df", accent: "#f3c400", roof: "#174f7d", windows: "#183d59" },
    fact: "metronom is known for blue-and-yellow locomotive-hauled double-deck trains.",
    source: source.metronom,
  },
  {
    id: "talent2",
    name: "DB Regio Talent 2",
    operator: "DB Regio",
    tier: 2,
    kind: "scheduled",
    style: "regional",
    cars: 4,
    dwell: [12, 17],
    payout: [95, 150],
    spawnWeight: 3,
    requirements: { platforms: 2, lengthLevel: 2, systems: ["electrification"] },
    modelKey: "talent2",
    colors: { body: "#e7e8e8", accent: "#d6122b", roof: "#899197", windows: "#153744" },
    fact: "Talent 2 electric units run in several lengths across German regional networks.",
    source: source.dbRegio,
  },
  {
    id: "flixtrain",
    name: "FlixTrain Refurbished Intercity",
    operator: "FlixTrain",
    tier: 3,
    kind: "scheduled",
    style: "intercity",
    cars: 10,
    dwell: [14, 19],
    payout: [320, 520],
    spawnWeight: 3,
    requirements: { platforms: 3, lengthLevel: 3, systems: ["electrification", "signaling"] },
    modelKey: "flixtrain",
    colors: { body: "#76bf43", accent: "#153d2c", roof: "#333b38", windows: "#152f37" },
    fact: "FlixTrain's current branded fleet comprises 140 fully refurbished coaches arranged into 10–20 trainsets.",
    source: source.flix,
  },
  {
    id: "ic1",
    name: "DB Intercity IC1",
    operator: "DB Fernverkehr",
    tier: 3,
    kind: "scheduled",
    style: "intercity",
    cars: 9,
    dwell: [15, 20],
    payout: [480, 720],
    spawnWeight: 3,
    requirements: { platforms: 3, lengthLevel: 4, systems: ["electrification", "signaling"] },
    modelKey: "ic1",
    colors: { body: "#eeeeea", accent: "#cf1530", roof: "#85898a", windows: "#1a3039" },
    fact: "Classic Intercity services pair electric locomotives with single-deck coaches.",
    source: source.dbFleet,
  },
  {
    id: "ic2",
    name: "DB Intercity 2",
    operator: "DB Fernverkehr",
    tier: 3,
    kind: "scheduled",
    style: "double",
    cars: 6,
    dwell: [15, 20],
    payout: [650, 900],
    spawnWeight: 2,
    requirements: { platforms: 3, lengthLevel: 3, systems: ["electrification", "signaling", "amenities"] },
    modelKey: "ic2",
    colors: { body: "#f2f1eb", accent: "#c9152d", roof: "#797f81", windows: "#203844" },
    fact: "Intercity 2 brought double-deck trains to DB long-distance service.",
    source: source.dbFleet,
  },
  {
    id: "ice2",
    name: "ICE 2",
    operator: "DB Fernverkehr",
    tier: 4,
    kind: "scheduled",
    style: "ice",
    cars: 8,
    dwell: [15, 20],
    payout: [1_500, 2_400],
    spawnWeight: 3,
    requirements: { platforms: 4, lengthLevel: 4, systems: ["electrification", "signaling", "maintenance"] },
    modelKey: "ice2",
    colors: { body: "#f4f2e9", accent: "#d1152e", roof: "#d8d8d2", windows: "#20343d" },
    fact: "ICE 2 sets use one power car and a driving trailer for flexible operation.",
    source: source.dbFleet,
  },
  {
    id: "ice3",
    name: "ICE 3",
    operator: "DB Fernverkehr",
    tier: 4,
    kind: "scheduled",
    style: "ice",
    cars: 8,
    dwell: [15, 20],
    payout: [2_400, 3_500],
    spawnWeight: 3,
    requirements: { platforms: 4, lengthLevel: 4, systems: ["electrification", "signaling", "maintenance"] },
    modelKey: "ice3",
    colors: { body: "#f7f4ea", accent: "#d3162f", roof: "#dfdfda", windows: "#1b313a" },
    fact: "ICE 3 distributes traction equipment beneath the train rather than using power cars.",
    source: source.dbFleet,
  },
  {
    id: "ice4",
    name: "ICE 4",
    operator: "DB Fernverkehr",
    tier: 4,
    kind: "scheduled",
    style: "ice",
    cars: 12,
    dwell: [16, 20],
    payout: [3_400, 4_500],
    spawnWeight: 2,
    requirements: { platforms: 4, lengthLevel: 4, systems: ["electrification", "signaling", "maintenance", "amenities"] },
    modelKey: "ice4",
    colors: { body: "#f5f3e9", accent: "#cd142d", roof: "#e0e0da", windows: "#182f39" },
    fact: "ICE 4 operates in seven-, twelve- and thirteen-car variants.",
    source: source.dbFleet,
  },
  {
    id: "railjet",
    name: "ÖBB Railjet",
    operator: "ÖBB",
    tier: 5,
    kind: "scheduled",
    style: "international",
    cars: 8,
    dwell: [16, 20],
    payout: [6_000, 9_000],
    spawnWeight: 3,
    requirements: { platforms: 4, lengthLevel: 4, systems: ["electrification", "signaling", "maintenance"] },
    modelKey: "railjet",
    colors: { body: "#a20d2e", accent: "#e7e0d2", roof: "#3b3437", windows: "#172e37" },
    fact: "Railjet is ÖBB's locomotive-hauled premium intercity train family.",
    source: "https://www.oebb.at/en/reiseplanung-services/im-zug/unsere-zuege/railjet",
  },
  {
    id: "nightjet",
    name: "ÖBB Nightjet",
    operator: "ÖBB",
    tier: 5,
    kind: "scheduled",
    style: "night",
    cars: 11,
    dwell: [18, 20],
    payout: [20_000, 20_000],
    spawnWeight: 2,
    requirements: { platforms: 5, lengthLevel: 5, systems: ["electrification", "signaling", "maintenance", "amenities"], nightOnly: true },
    modelKey: "nightjet",
    colors: { body: "#10244f", accent: "#38a8dd", roof: "#101a31", windows: "#f4d26c" },
    fact: "Nightjet consists vary from 3–11 coaches and link German cities with overnight destinations across Europe.",
    source: source.nightjet,
  },
  {
    id: "tgv-duplex",
    name: "TGV Euroduplex",
    operator: "SNCF Voyageurs",
    tier: 5,
    kind: "scheduled",
    style: "international",
    cars: 10,
    dwell: [16, 20],
    payout: [8_000, 13_000],
    spawnWeight: 2,
    requirements: { platforms: 5, lengthLevel: 5, systems: ["electrification", "signaling", "maintenance"] },
    modelKey: "tgv-duplex",
    colors: { body: "#e6e5df", accent: "#6c3a8f", roof: "#777b80", windows: "#243642" },
    fact: "The Euroduplex is a double-deck TGV designed for international networks.",
    source: "https://www.sncf-voyageurs.com/en/travel-with-us/train-and-services/tgv-inoui/",
  },
  {
    id: "regiojet-cz",
    name: "RegioJet International",
    operator: "RegioJet",
    tier: 5,
    kind: "scheduled",
    style: "international",
    cars: 9,
    dwell: [16, 20],
    payout: [7_000, 11_000],
    spawnWeight: 2,
    requirements: { platforms: 4, lengthLevel: 4, systems: ["electrification", "signaling", "roadAccess"] },
    modelKey: "regiojet-cz",
    colors: { body: "#f2cf00", accent: "#202020", roof: "#464646", windows: "#20333c" },
    fact: "RegioJet is a Czech private operator running international services.",
    source: "https://regiojet.com/",
  },
  {
    id: "giruno",
    name: "SBB Giruno",
    operator: "SBB",
    tier: 5,
    kind: "scheduled",
    style: "international",
    cars: 11,
    dwell: [16, 20],
    payout: [10_000, 15_000],
    spawnWeight: 2,
    requirements: { platforms: 5, lengthLevel: 5, systems: ["electrification", "signaling", "maintenance", "amenities"] },
    modelKey: "giruno",
    colors: { body: "#e9e8e3", accent: "#d71920", roof: "#595e61", windows: "#1a3742" },
    fact: "The Giruno is built for international service between Switzerland, Germany and Italy.",
    source: source.sbb,
  },
  {
    id: "comfortjet",
    name: "ČD ComfortJet",
    operator: "České dráhy",
    tier: 5,
    kind: "scheduled",
    style: "international",
    cars: 9,
    dwell: [16, 20],
    payout: [12_000, 18_000],
    spawnWeight: 2,
    requirements: { platforms: 5, lengthLevel: 5, systems: ["electrification", "signaling", "maintenance", "amenities"] },
    modelKey: "comfortjet",
    colors: { body: "#e8eef0", accent: "#1267a4", roof: "#50636c", windows: "#183744" },
    fact: "ComfortJet sets are designed for modern international services including Berlin.",
    source: source.cd,
  },
  {
    id: "ice-s",
    name: "ICE-S Record Run",
    operator: "DB Systemtechnik",
    tier: 4,
    kind: "event",
    style: "measurement",
    cars: 3,
    dwell: [10, 12],
    payout: [25_000, 25_000],
    spawnWeight: 0,
    requirements: { platforms: 4, lengthLevel: 4, systems: ["electrification", "signaling", "advancedSignaling"] },
    modelKey: "ice-s",
    colors: { body: "#f2f0e8", accent: "#80878b", roof: "#d7d7d0", windows: "#18343e" },
    fact: "DB's 76 m ICE-S measurement train reached 398 km/h during a 2001 bogie test.",
    source: source.iceS,
  },
  {
    id: "br01",
    name: "BR 01 Steam Festival",
    operator: "Heritage special",
    tier: 2,
    kind: "event",
    style: "steam",
    cars: 6,
    dwell: [18, 20],
    payout: [3_000, 3_000],
    spawnWeight: 0,
    requirements: { platforms: 2, lengthLevel: 2, systems: [] },
    modelKey: "br01",
    colors: { body: "#17191a", accent: "#b42025", roof: "#111213", windows: "#e9b75e" },
    fact: "Museum locomotive 01 1100 was built in 1940; the 01.10 class reached 140 km/h on heavy express work.",
    source: source.steam,
  },
];

export const MISSIONS: Record<MissionState["id"], { title: string; goal: number; reward: number; description: string }> = {
  serve: { title: "Reliable rhythm", goal: 5, reward: 120, description: "Serve 5 trains." },
  develop: { title: "Build momentum", goal: 2, reward: 180, description: "Purchase 2 permanent upgrades." },
  clean: { title: "Fresh platforms", goal: 1, reward: 90, description: "Clean the station once." },
};

export const REGIONS: { id: RegionId; name: string; subtitle: string; enabled: boolean; mark: string }[] = [
  { id: "germany", name: "Germany", subtitle: "Regional rails to international icons", enabled: true, mark: "DE" },
  { id: "china", name: "China", subtitle: "Coming soon", enabled: false, mark: "CN" },
  { id: "france", name: "France", subtitle: "Coming soon", enabled: false, mark: "FR" },
  { id: "japan", name: "Japan", subtitle: "Coming soon", enabled: false, mark: "JP" },
];

export function createInitialState(prestige = 0): GameState {
  return {
    saveVersion: 1,
    region: null,
    platformPlaced: false,
    coins: 0,
    lifetimeCoins: 0,
    tier: 1,
    upgradesUsed: 0,
    platforms: 1,
    lengthLevel: 1,
    systems: {
      electrification: false,
      signaling: false,
      roadAccess: false,
      maintenance: false,
      amenities: false,
      advancedSignaling: false,
    },
    cleanliness: 100,
    speed: 1,
    simSeconds: 0,
    wallSeconds: 0,
    platformLanes: [{ platformIndex: 0, spawnCountdown: 2, activeTrain: null }],
    firstTrainComplete: false,
    arrivals: 0,
    prestige,
    raining: false,
    rainRemaining: 0,
    seasonIndex: 0,
    nextSeasonAt: 1_800,
    eventWindow: null,
    eventRemaining: 0,
    boosts: [],
    mission: { id: "serve", progress: 0, complete: false },
    lastUpgrade: null,
    rng: 0x5f3759df,
    toast: null,
  };
}
